$\nabla^2u = f(x,y), 0\leq x\leq1, 0\leq y\leq1 \\ f(x,y) = -32\big( x(1-x)+y(1-y)\big), u\big|_{x,y \in Г} = 0 \\ \varepsilon = 10^{-6}$

Возьмем $N_1 = 8$ и $N_2 = 6$ точек по двум направлениям. Тогда шаг: $h_1 = \frac{1}{8}$, $h_2 = \frac{1}{6}.$

Зададим начальные значения $u^{(0)}_{i,j} = 0$ для внутренних точек и присвоим заданные значения $u_{i, j} = 0$ для граничных

Реализуем $\textit{алгоритм Зейделя}$ в виде:  

$u_{i,j}^{(k)} = \Bigg(\frac{u_{i,j-1}^{(k)} + u_{i,j+1}^{(k-1)}}{h_1^2} + \frac{u_{i-1,j}^{(k)} + u_{i+1,j}^{(k-1)}}{h_2^2} - f_{i,j}\Bigg)/\Bigg(\frac{2}{h_1^2} + \frac{2}{h_2^2}\Bigg), j = 1, ..., N_1 -1, i = 1,..., N_2 - 1, k = 1,2,...$

$k$ - номер итерации 

Счет ведется до тех пор, пока не будет выполнено следующее: 

$z_k = \sum\limits_{i = 1}^{N_2 - 1}\sum\limits_{j = 1}^{N_1 - 1}\big|u_{i,j}^{(k)} - u_{i,j}^{(k-1)}\big| < \varepsilon$

In [121]:
def f(x,y):
    if 0 <= x <= 1 and 0 <= y <= 1:
        return -32*(x*(1-x) + y*(1-y))
    else: 
        return 0

In [146]:
N_1 = 6 #число разбиений 
N_2 = 8

In [147]:
h_1 = 1/N_1 #шаг
h_2 = 1/N_2

In [124]:
import numpy as np

In [164]:
u = np.ones((N_1,N_2))

In [165]:
print(u)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [166]:
for i in range(0,N_1):#учитываем значения u на границе 
    for j in range(0,N_2):
        if j == 0 or j == N_2-1:
            u[i,j] = 0
        if i == 0 or i == N_1-1:
            u[i,j] = 0

In [167]:
print(u)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [168]:
%%time
#непосредственное вычисление методом Зейделя 

k = 0
idi = 0
while idi == 0:
    for i in range(1,N_1-1):
        for j in range(1,N_2-1):
            r = u
            u[i,j] = ((u[i,j-1] + u[i,j+1])/(h_1**2) + (u[i-1,j] + u[i+1,j])/(h_2**2) - f(i,j))/(2/(h_1**2) + 2/(h_2**2))
            z = abs(u[i,j] - r)
    k = k + 1
    if z.all() < 0.000001 and k < 100:
        idi = 1

Wall time: 0 ns


In [181]:
#итоговая матрица ответов
for i in range(0,N_1):
    for j in range(0,N_2):
        u[i,j] = round(u[i,j],4)        
print(u)


[[0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.5    0.59   0.6062 0.6091 0.6096 0.4297 0.    ]
 [0.     0.66   0.8076 0.8394 0.846  0.8474 0.61   0.    ]
 [0.     0.7112 0.8864 0.9282 0.9378 0.94   0.6844 0.    ]
 [0.     0.4076 0.537  0.5737 0.5834 0.5858 0.3245 0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.    ]]
